name: Ansible

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      # Git Clone/Pull
      - uses: actions/checkout@v3

      - name: Generate Key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key
          chmod 400 ansible_key

      - name: Install Python Prerequisites
        run: |
          /opt/pipx/venvs/ansible-core/bin/activate
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 boto botocore

      - name: Run Ansible Playbook
        run: ansible-playbook -i aws_ec2.yml --private-key=ansible_key main.yml -u ec2-user -b 
